apiVersion: v1
kind: Service
metadata:
  name: devsu-devops-technical-test-nodejs-service
spec:
  type: ClusterIP
  selector:
    app: devsu-devops-technical-test-nodejs
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}
