awsEcrImageUrl: 875649895777.dkr.ecr.us-east-1.amazonaws.com/devsu-project-repo-devsu-prod:latest
nodeEnv: production
replicaCount: 2
containerPort: 8000
database:
    name: devsu_db
    user: admin
    password: password123
